# # theme: jekyll-theme-minimal
title: "Yoga ASISaga - The Mind of Artificial Superintelligence"
description: "Exploring the parts of mind in the context of Artificial Superintelligence"
ignore_theme_config: true

sass:
  load_paths:
    - _sass
    - assets/css

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

remote_theme: ASISaga/theme.asisaga.com@main

# Exclude specific directories and files from being processed by Jekyll
exclude:
  - docs/
  - LICENSE
  - README.md
  - website_structure.json

# The defaults section allows you to set default values for certain variables
  # The scope key defines the default values for specific types of files
  - scope:
      path: "" # Applies to all files in your site
      type: "html" # Targets only HTML files
    values: # Default values for the specified scope
      layout: default # The name of the layout you want to apply
